### ISSUE TITLE
Error in package.json

### ISSUE THREAD

**Issue by rianby64** [gregorylimoratto/karma-jasmine-feature#1]
Hello Gregory!
I'm trying your solution karma-jasmine-feature and I'm doing the next>
1) clone
2) npm install
3) npm test

But something is wrong with npm install:
"Error: version not found: 1.0.0 : karma-jasmine-feature/1.0.0"

So, I'm deleting from package.json the line that points to karma-jasmine-feature, then everything got installed and then npm test shows me that all is right.
What I am doing wrong?

Thanks a lot in advance

**Comment by gregorylimoratto** [comment]
Hello !
I reassure you , you do nothing wrong. I fixed the package.json, this dependency should not be here :)

Thanks for the remark

**Comment by rianby64** [comment]
Do you've email? I want to ask you some things about this solution. Please, contact me at rianby64@gmail.com
