### ISSUE TITLE
Please add simple sample

### ISSUE THREAD

**Issue by itsimoshka** [gregorylimoratto/karma-jasmine-feature#2]
Hi! Thank you for lib
But in your example you use relative paths like `require.resolve('./lib/adapter.js')`. 
Can you please provide sample where you lib will be installed with `npm`?

**Comment by gregorylimoratto** [comment]
Hi,
No need to use require.resolve('./lib/adapter.js');
The adapter and preprocessor are automatically load by karma by simply use ;
    frameworks: ['jasmine', 'jasmine-feature'],
in karma.conf.js.
Tell me if it's confusing, i'll post a config sample

**Comment by itsimoshka** [comment]
@gregorylimoratto thank you!

**Comment by rianby64** [comment]
https://github.com/rianby64/karma-jasmine-feature-example I wrote that a long time ago... Hope this may help you.
