### ISSUE TITLE
Done function

### ISSUE THREAD

**Issue by itsimoshka** [gregorylimoratto/karma-jasmine-feature#3]
Please add Jasmine done() function for testing acync code

**Comment by gregorylimoratto** [comment]
Hello,
Excuse me for the late reply. 
In fact, it already works with async as you use promises. 
You just have to return the promise in a step and the lib will wait for it to complete to chain next steps.
Here is an sample : 
.when(/I have a promise setting '(._)' in context after (\d+) ms/, function(message, ms){ 
    var defer = this.promise.defer();
    var self = this;
    setTimeout(function(){
        self.message = message;
        defer.resolve();
    }, ms);
    return defer.promise;
})
.then(/I have '(._)' in context/,function(message){
     expect(this.message).toBe(message); 
});

(In this sample I use $Q)

**Comment by itsimoshka** [comment]
@gregorylimoratto thank you very mutch
